# Generated by Django 4.1 on 2022-09-05 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "verbose_name_plural": "Amenities",
            },
            bases=("core.timestampmodel",),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "verbose_name_plural": "Academies",
                "ordering": ["name"],
            },
            bases=("core.timestampmodel",),
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "verbose_name_plural": "Facilites",
            },
            bases=("core.timestampmodel",),
        ),
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=80)),
                ("adress", models.CharField(max_length=140)),
                ("price", models.IntegerField()),
                ("booking", models.TimeField()),
                ("guests", models.IntegerField()),
                ("instant_book", models.BooleanField(default=False)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="academies", to="academies.amenity"
                    ),
                ),
                (
                    "events",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academies",
                        to="academies.event",
                    ),
                ),
                (
                    "facility",
                    models.ManyToManyField(
                        blank=True, related_name="academies", to="academies.facility"
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.timestampmodel",),
        ),
    ]
