# Generated by Django 4.1 on 2022-09-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("academies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                ("caption", models.CharField(max_length=100)),
                ("file", models.ImageField(upload_to="academy_photos")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="academies.academy",
                    ),
                ),
            ],
            bases=("core.timestampmodel",),
        ),
    ]
