# Generated by Django 4.1 on 2022-09-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academy",
            options={"ordering": ["name"], "verbose_name_plural": "Academies"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["name"], "verbose_name_plural": "Events"},
        ),
    ]
