# Generated by Django 4.1 on 2022-09-05 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conversation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.timestampmodel",),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                ("Message", models.TextField()),
                (
                    "conversations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="massages",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="massages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.timestampmodel",),
        ),
    ]
