# Generated by Django 4.1 on 2022-09-05 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("academies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampmodel",
                    ),
                ),
                ("Review", models.TextField()),
                ("accurancy", models.IntegerField()),
                ("communication", models.IntegerField()),
                ("professionality", models.IntegerField()),
                ("location", models.IntegerField()),
                ("booking", models.IntegerField()),
                ("value", models.IntegerField()),
                (
                    "Academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="academies.academy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.timestampmodel",),
        ),
    ]
